### ISSUE TITLE
How to visualize the performance after "sh ./train_expert.sh"?

### ISSUE THREAD

**Issue by Charlie0257** [tianhaowuhz/DexFunPreGrasp#1]
Hi, @tianhaowuhz 
Thanks for your great work!

How to visualize the performance after "sh ./train_expert.sh"?

Best,
Charlie

**Comment by tianhaowuhz** [comment]
you can run with the following context, which is simply changing mode to eval and load pretrain ckpt:
```
python src/train.py \
    mode="eval" \
    env_mode=pgm \
    env_info=False \
    num_envs=12000 \
    num_objects=-1 \
    num_objects_per_env=1 \
    graphics_device_id=0 \
    split='train' \
    cluster=0 \
    task.env.datasetMetainfoPath="data/oakink_filtered_metainfo.csv" \
    task.env.datasetPoseLevelSampling=True \
    --seed=0 \
    --exp_name='PPO' \
    --logdir='your log dir' \
    --run_device_id=0 \
    --web_visualizer_port=-1 \
    --model_dir="you ckpt here" \
```

**Comment by Charlie0257** [comment]
@tianhaowuhz Thanks for your reply!

When I try the command you suggested, I still can't visualize how the agent behaves. When I try to change `graphics_device_id=0`, the program reports a `Segmentation fault      (core dumped)` error.

Thanks for any help!

Best,
Charlie

**Comment by tianhaowuhz** [comment]
This problem is probably due to you running the script on a server without monitor, render of isaacgym must going on a local compute instead of docker

**Comment by tianhaowuhz** [comment]
This can be caused by two reason: 1. You are running script on a docker without monitor. 2. Your computer does have enough memory to load all objects and open 12000 environments, try to set num_envs to 10, and num_objects to 2. I also update the above shell, since some args also need to change for visualization.

**Comment by Charlie0257** [comment]
@tianhaowuhz Thanks for your reply!

When I try to set `num_objects to 2`, the visualization is finally working:)

By the way, will the subsequent content in Item A be updated in the near future? I'm looking forward to the full content!

**Comment by tianhaowuhz** [comment]
No problem, we are busy with one project recently, and will public soon.

**Comment by Charlie0257** [comment]
Thanks :)
