### ISSUE TITLE
Inquiry About Computational Resources for Training Teacher and Student Policies

### ISSUE THREAD

**Issue by xiaopangxiexyg** [tianhaowuhz/DexFunPreGrasp#2]
Hi, @tianhaowuhz
Thanks for your great work!

Can you share the GPU specs, memory usage, and training time for both the teacher and student policy training?
Any information you can share would be greatly appreciated!

Thanks,
Yingge

**Comment by tianhaowuhz** [comment]
For expert policy training, the duration varies across clusters, as each cluster involves different objects and poses. Most clusters take around 2-3 days to complete (around 15k-20k , the total is 40k currently). While I did not record GPU memory usage, 24 GB should be sufficient for training on a single cluster. For diffusion policy distillation, the training time depends on the number of samples per pose; for instance, with 5, 10, or 20 samples per pose, training takes approximately 1, 2.5, and 4 days, respectively. This process generally requires 24-32 GB of GPU memory. The training time is computed with only one GPU card for training, and times can change with hardware, such as parallel training, more CPU.

**Comment by xiaopangxiexyg** [comment]
Thank you for your detailed response.

I currently have 2-3 GTX 3090 GPUs with a total of 48-72 GB of memory (24 GB per card). I wanted to check if this configuration would provide sufficient computational power for training. Could you also please share which specific GPU model you are using for training(e.g., A100, H100, etc.)?

**Comment by tianhaowuhz** [comment]
For expert policy training on a single cluster, a 3090 GPU should be sufficient. For student training on a single card, 24 GB of memory may not be enough; however, you can reduce the batch size.

**Comment by xiaopangxiexyg** [comment]
Thank you so much for your response!

Also, I saw your note about this being an early version of the release. I’m excited to see the upcoming updates and improvements in the next version!✨
